# Generated by Django 4.1.1 on 2024-06-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
