# Generated by Django 4.1.1 on 2024-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_event_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='district',
            field=models.CharField(choices=[('PR', 'Praha'), ('ST', 'Středočeský kraj'), ('PL', 'Plzeňský kraj'), ('KU', 'Karlovarský kraj'), ('UL', 'Ústecký kraj'), ('LI', 'Liberecký kraj'), ('HA', 'Královéhradecký kraj'), ('PA', 'Pardubický kraj'), ('JI', 'Jihočeský kraj'), ('VY', 'Vysočina'), ('MO', 'Moravskoslezský kraj'), ('SO', 'Olomoucký kraj'), ('ZL', 'Zlínský kraj')], default='PR', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
