# Generated by Django 4.1.1 on 2024-06-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_event_district_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='district',
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(choices=[('JM', 'Jihomoravský'), ('JC', 'Jihočeský'), ('KA', 'Karlovarský'), ('KR', 'Královéhradecký'), ('LI', 'Liberecký'), ('MO', 'Moravskoslezský'), ('OL', 'Olomoucký'), ('PA', 'Pardubický'), ('PL', 'Plzeňský'), ('PR', 'Praha'), ('ST', 'Středočeský'), ('US', 'Ústecký'), ('VY', 'Vysočina'), ('ZL', 'Zlínský')], default='PR', max_length=40),
        ),
    ]
