# Generated by Django 4.1.1 on 2024-06-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_remove_event_district_event_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(choices=[('JM', 'Jihomoravský'), ('JC', 'Jihočeský'), ('KA', 'Karlovarský'), ('KR', 'Královéhradecký'), ('LI', 'Liberecký'), ('MO', 'Moravskoslezský'), ('OL', 'Olomoucký'), ('PA', 'Pardubický'), ('PL', 'Plzeňský'), ('PR', 'Praha'), ('ST', 'Středočeský'), ('US', 'Ústecký'), ('VY', 'Vysočina'), ('ZL', 'Zlínský')], default='', max_length=40),
        ),
    ]
