# Generated by Django 4.1.1 on 2024-07-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_event_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='region',
        ),
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
